services:
  api:
    build: ./app
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      DATA_DIR: "/data"
      DUCKDB_PATH: "/data/staging.duckdb"
    volumes:
      - .:/app
      - ./data:/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ./app
    working_dir: /app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      DATA_DIR: "/data"
      DUCKDB_PATH: "/data/staging.duckdb"
    volumes:
      - .:/app
      - ./data:/data
    command: python -u -m app.watcher